### ISSUE TITLE
ERROR: Could not build wheels for backports.zoneinfo, which is required to install pyproject.toml-based projects?

### ISSUE THREAD

**Issue by yabesh12** [pganssle/zoneinfo#117]
when I run docker-compose build it seems to stop middle when executing the Dockerfile. Have no idea about this. please need assistance to run this?

**Comment by andre-bandeli** [comment]
I have same issue

**Comment by yabesh12** [comment]
@andre-bandeli  I have issue with the Dockerfile. after i corrected the Dockerfile it was solved.
Dockerfile
---------------
`FROM python:3.8.10
ENV PYTHONUNBUFFERED=1
RUN apt-get update
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/`
