### ISSUE TITLE
ZoneInfo('America/Mexico_City') subtracts one hour less from UTC

### ISSUE THREAD

**Issue by tribumirkov** [pganssle/zoneinfo#138]
Hey folks,

Mexico decided not to move any more to summer time from 2023 on (don't ask me why):

https://www.marca.com/mx/actualidad/2023/03/28/6423471a46163f89688b45c3.html

ZoneInfo should therefore be adjusted. 

To reproduce the error:

from zoneinfo import ZoneInfo
from datetime import datetime

utc = datetime.utcnow()
mexican_zone = ZoneInfo('America/Mexico_City')
local = utc.replace(tzinfo=timezone.utc).astimezone(mexican_zone)
print(local)

Thank you!

**Comment by pganssle** [comment]
ZoneInfo does not hard code the zones, they are provided by your operating system or `tzdata`
