### ISSUE TITLE
Failed building wheel for backports-zoneinfo

### ISSUE THREAD

**Issue by Tim-Kirkwood** [pganssle/zoneinfo#139]
***CONTEXT***

I've been having dependency issues after installing `Python 3.9` (discussed [here][1] and [here][2]).  The issues in the linked posts have been fixed, but I am uninstalling and re-installing my `pip`-installed packages to make sure they are compatible with my new python version.  One of the packages I am trying to do this with is `backports-zoneinfo`.  I am aware I [don't really need this][3], but I was going to keep it anyway in case I write something needing compatibility with older python versions.  

***ISSUE:***

I have uninstalled `backports-zoneinfo`, and then tried to reinstall it, but get the error message at the bottom of this post.  I then installed [build tools 2022][4] as per the error message and tried to re-install `backports-zoneinfo` again, but got the same error.  Please can someone help me to diagnose and fix the issue?

Thank you!

***Uninstall message:***

    C:\Users\u03132tk>pip uninstall backports-zoneinfo
    WARNING: Ignoring invalid distribution -umpy (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umexpr (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -iopython (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -illow (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -cipy (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umpy (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umexpr (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -iopython (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -illow (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -cipy (c:\anaconda3\lib\site-packages)
    Found existing installation: backports.zoneinfo 0.2.1
    Uninstalling backports.zoneinfo-0.2.1:
      Would remove:
        c:\anaconda3\lib\site-packages\backports.zoneinfo-0.2.1.dist-info\*
        c:\anaconda3\lib\site-packages\backports\*
      Would not remove (might be manually added):
        c:\anaconda3\lib\site-packages\backports\functools_lru_cache.py
        c:\anaconda3\lib\site-packages\backports\tempfile.py
        c:\anaconda3\lib\site-packages\backports\weakref.py
    Proceed (Y/n)? Y
      Successfully uninstalled backports.zoneinfo-0.2.1

***Reinstall error***  

    C:\Users\u03132tk>pip install backports-zoneinfo
    WARNING: Ignoring invalid distribution -umpy (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umexpr (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -iopython (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -illow (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -cipy (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umpy (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umexpr (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -iopython (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -illow (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -cipy (c:\anaconda3\lib\site-packages)
    Collecting backports-zoneinfo
      Using cached backports.zoneinfo-0.2.1.tar.gz (74 kB)
      Installing build dependencies ... done
      Getting requirements to build wheel ... done
      Preparing metadata (pyproject.toml) ... done
    Building wheels for collected packages: backports-zoneinfo
      Building wheel for backports-zoneinfo (pyproject.toml) ... error
      error: subprocess-exited-with-error
    
      × Building wheel for backports-zoneinfo (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [46 lines of output]
          C:\Users\u03132tk\AppData\Local\Temp\pip-build-env-0o6uoggk\overlay\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
          !!
    
                  ********************************************************************************
                  The license_file parameter is deprecated, use license_files instead.
    
                  By 2023-Oct-30, you need to update your project and remove deprecated calls
                  or your builds will no longer be supported.
    
                  See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                  ********************************************************************************
    
          !!
            parsed = self.parsers.get(option_name, lambda x: x)(value)
          running bdist_wheel
          running build
          running build_py
          creating build
          creating build\lib.win-amd64-cpython-39
          creating build\lib.win-amd64-cpython-39\backports
          copying src\backports\__init__.py -> build\lib.win-amd64-cpython-39\backports
          creating build\lib.win-amd64-cpython-39\backports\zoneinfo
          copying src\backports\zoneinfo\_common.py -> build\lib.win-amd64-cpython-39\backports\zoneinfo
          copying src\backports\zoneinfo\_tzpath.py -> build\lib.win-amd64-cpython-39\backports\zoneinfo
          copying src\backports\zoneinfo\_version.py -> build\lib.win-amd64-cpython-39\backports\zoneinfo
          copying src\backports\zoneinfo\_zoneinfo.py -> build\lib.win-amd64-cpython-39\backports\zoneinfo
          copying src\backports\zoneinfo\__init__.py -> build\lib.win-amd64-cpython-39\backports\zoneinfo
          running egg_info
          writing src\backports.zoneinfo.egg-info\PKG-INFO
          writing dependency_links to src\backports.zoneinfo.egg-info\dependency_links.txt
          writing requirements to src\backports.zoneinfo.egg-info\requires.txt
          writing top-level names to src\backports.zoneinfo.egg-info\top_level.txt
          reading manifest file 'src\backports.zoneinfo.egg-info\SOURCES.txt'
          reading manifest template 'MANIFEST.in'
          warning: no files found matching '*.png' under directory 'docs'
          warning: no files found matching '*.svg' under directory 'docs'
          no previously-included directories found matching 'docs\_build'
          no previously-included directories found matching 'docs\_output'
          adding license file 'LICENSE'
          adding license file 'licenses/LICENSE_APACHE'
          writing manifest file 'src\backports.zoneinfo.egg-info\SOURCES.txt'
          copying src\backports\zoneinfo\__init__.pyi -> build\lib.win-amd64-cpython-39\backports\zoneinfo
          copying src\backports\zoneinfo\py.typed -> build\lib.win-amd64-cpython-39\backports\zoneinfo
          running build_ext
          building 'backports.zoneinfo._czoneinfo' extension
          error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
          [end of output]
    
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for backports-zoneinfo
    Failed to build backports-zoneinfo
    ERROR: Could not build wheels for backports-zoneinfo, which is required to install pyproject.toml-based projects
    WARNING: Ignoring invalid distribution -umpy (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umexpr (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -iopython (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -illow (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -cipy (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umpy (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umexpr (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -iopython (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -illow (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -cipy (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umpy (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umexpr (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -iopython (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -illow (c:\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -cipy (c:\anaconda3\lib\site-packages)

  [1]: https://stackoverflow.com/questions/76320554/import-errors-after-updating-spyder-and-python?noredirect=1#comment134584293_76320554
  [2]: https://stackoverflow.com/questions/76314158/spyder-kernels-anaconda-and-python-3-9/76320534?noredirect=1#comment134585043_76320534
  [3]: https://stackoverflow.com/a/72796492/11357695
  [4]: https://visualstudio.microsoft.com/visual-cpp-build-tools/?fbclid=IwAR2CjL1xcjVN8PCHAszkPfVFix-1Iosqn_wbvp9Ij8whDsQyTKDNe-66nfs

**Comment by Tim-Kirkwood** [comment]
I tried [clearing my pip cache](https://stackoverflow.com/a/61762308/11357695) due to the error line `Using cached backports.zoneinfo-0.2.1.tar.gz (74 kB)` (maybe the cached version is broken/old and incompatible with other packages) - but this made no difference other than removing that line from the cmd line output

**Comment by bellyhold** [comment]
My team is seeing the same issue starting this morning. Any workarounds or fixes?

**Comment by pganssle** [comment]
I think the solution is to just declare a conditional dependency on `backports.zoneinfo`, like this:

```python
backports.zoneinfo;python_version<"3.9"
```

Per [this note in the readme](https://github.com/pganssle/zoneinfo#installation-and-depending-on-this-library).
