### ISSUE TITLE
Build problem on AIX

### ISSUE THREAD

**Issue by isidentical** [pganssle/zoneinfo#37]
As this module is going to be merged back in CPython (hopefully), I wanted to try it on one of the systems we are supporting as [Best effort](https://pythondev.readthedocs.io/platforms.html#best-effort-and-unofficial-platforms) and looks like it needs a little header shift

```
Batuhan, [15.04.20 21:47]
"/usr/include/stdio.h", line 558.12: 1506-343 (S) Redeclaration of fgetpos64 differs from previous declaration on line 353 of "/usr/include/stdio.h".
"/usr/include/stdio.h", line 558.12: 1506-377 (I) The type "long long*" of parameter 2 differs from the previous type "long* restrict".
"/usr/include/stdio.h", line 561.12: 1506-343 (S) Redeclaration of fseeko64 differs from previous declaration on line 501 of "/usr/include/stdio.h".
"/usr/include/stdio.h", line 561.12: 1506-377 (I) The type "long long" of parameter 2 differs from the previous type "long".
"/usr/include/stdio.h", line 562.12: 1506-343 (S) Redeclaration of fsetpos64 differs from previous declaration on line 355 of "/usr/include/stdio.h".
"/usr/include/stdio.h", line 562.12: 1506-377 (I) The type "const long long*" of parameter 2 differs from the previous type "const long*".
"/usr/include/stdio.h", line 563.16: 1506-343 (S) Redeclaration of ftello64 differs from previous declaration on line 502 of "/usr/include/stdio.h".
"/usr/include/stdio.h", line 563.16: 1506-050 (I) Return type "long long" in redeclaration is not compatible with the previous return type "long".
"/usr/include/unistd.h", line 201.17: 1506-343 (S) Redeclaration of lseek64 differs from previous declaration on line 199 of "/usr/include/unistd.h".
"/usr/include/unistd.h", line 201.17: 1506-050 (I) Return type "long long" in redeclaration is not compatible with the previous return type "long".
"/usr/include/unistd.h", line 201.17: 1506-377 (I) The type "long long" of parameter 2 differs from the previous type "long".
"/usr/include/sys/lockf.h", line 64.20: 1506-343 (S) Redeclaration of lockf64 differs from previous declaration on line 62 of "/usr/include/sys/lockf.h".
```
(and goes like this). After a bit digging I encountered with a fix for the same issue from pycrypto folks, and they wrote

> The problem is that the pycrypto source files do not #include "Python.h"
before all other includes. In general, you would always want to include
all standard libraries first(i.e. #include <string.h> ...) However,
with Python.h this is bad. The reason is that Python.h includes
pyconfig.h which has defines intended to define system level compiler
directives for the particular platform. These would of course need to
be defined before all standard header files otherwise, the standard
header files before the Python.h include would not have the system
defines and the standard header files after the Python.h include would.

And after shifting it, looks like it works.

**Comment by pganssle** [comment]
@isidentical Thanks for this report! I've opened #38 to fix it.
