### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [pganssle/zoneinfo#99]
Problem
---------
On aarch64, ‘pip install backports.zoneinfo’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install backports.zoneinfo’ should download the wheels from pypi

@pganssle Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by pganssle** [comment]
Yes, I'm very happy to release aarch64 wheels, thank you and sorry for the oversight in not having included them in the first place!

**Comment by pganssle** [comment]
Fixed in #100. I will make a 0.2.2 release shortly.
